[project]
name = "mcp-httpx"
version = "0.1.0"
description = "MCP server for rest api testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.0",
]
